version: '3.8'

services:
  api:
    image: node-api:v5
    container_name: node-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    command: sh -c "npx prisma db push && npm run start:dev"
  
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tock_tock
    ports:
      - '5432:5432'
    volumes:
      - ./docker/data:/var/lib/postgresql/data
